theme: minima
description: Kevin Ashley, Author
author: Kevin Ashley
title: Kevin Ashley
description: Books, Art, Code and Resources
layout: home
twitter_username: kashleytwit
github_username:  kevinash
instagram_username: awesomeai_art
