theme: minima
description: Kevin Ashley, Author
title: Kevin Ashley Labs
description: Products, Projects, Books, Art, Code and Resources
layout: home
linkedin_username: kashlik
twitter_username: kashleytwit
github_username:  kevinash
instagram_username: awesomeai_art